# Generated by Django 3.0.2 on 2020-01-08 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='start_group',
            new_name='group_target',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='eats',
            new_name='food',
        ),
        migrations.AddField(
            model_name='participant',
            name='group',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='group_role',
            field=models.IntegerField(choices=[(0, ''), (1, 'Scorer'), (2, 'Captain')], default=0, verbose_name='Archer role'),
        ),
        migrations.AlterField(
            model_name='archer',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.Club'),
        ),
        migrations.AlterField(
            model_name='archer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archer', to=settings.AUTH_USER_MODEL),
        ),
    ]
