# Generated by Django 3.0.2 on 2020-01-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200108_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scorecard',
            options={'ordering': ['-participant__group_role']},
        ),
        migrations.AddField(
            model_name='event',
            name='admins',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='event admins'),
        ),
        migrations.AddField(
            model_name='event',
            name='records',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='record category (nat/EM/MM)'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='score',
            field=models.IntegerField(default=None, null=True, verbose_name='Final score'),
        ),
    ]
