# Generated by Django 3.0.2 on 2020-01-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200119_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scorecard',
            options={'ordering': ['participant__group_pos']},
        ),
        migrations.RemoveField(
            model_name='participant',
            name='group_role',
        ),
        migrations.AddField(
            model_name='participant',
            name='group_pos',
            field=models.CharField(default='', max_length=1, verbose_name='Archer position'),
        ),
    ]
