# Generated by Django 2.2.6 on 2019-11-01 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191101_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
