# Generated by Django 3.0.2 on 2020-01-23 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200122_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='name_short',
            field=models.CharField(blank=True, default='***', max_length=10, verbose_name='Club name short'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='comments',
            field=models.CharField(blank=True, max_length=255, verbose_name='Comments to organiser'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='group',
            field=models.IntegerField(default=None, null=True, verbose_name='Group/Target nr'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='group_pos',
            field=models.CharField(blank=True, default='', max_length=1, verbose_name='Archer position'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='group_target',
            field=models.IntegerField(default=1, verbose_name='Starting end nr'),
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_start', models.DateField(default=django.utils.timezone.localdate)),
                ('date_end', models.DateField(default=django.utils.timezone.localdate)),
                ('name', models.CharField(default='Unnamed Series', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('private', 'Private'), ('club', 'Club'), ('open', 'Open')], default='private', max_length=10, verbose_name='event type')),
                ('participant_restriction', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='i.e. club__association')),
                ('participant_min', models.IntegerField(default=1, verbose_name='Minimum nr of events for final ranking')),
                ('participant_max', models.IntegerField(default=None, null=True, verbose_name='Maximum nr of envets used for final ranking')),
                ('club_ranking', models.BooleanField(default=False)),
                ('club_ranking_max', models.IntegerField(default=3, verbose_name='Max nr of club members to contribute points to club per class')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
