# Generated by Django 3.0.2 on 2020-05-27 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200123_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archer', models.CharField(max_length=255, verbose_name='Archer name')),
                ('event', models.CharField(blank=True, max_length=255, verbose_name='Competition')),
                ('age_group', models.CharField(choices=[('C', 'Cub'), ('J', 'Junior'), ('A', 'Adult'), ('V', 'Veteran'), ('S', 'Senior')], max_length=1, verbose_name='age group')),
                ('style', models.CharField(choices=[('BB-C', 'Barebow Compound'), ('BB-R', 'Barebow Recurve'), ('BH-C', 'Bowhunter Compound'), ('BH-R', 'Bowhunter Recurve'), ('BL', 'Bowhunter Limited'), ('BU', 'Bowhunter Unlimited'), ('FS-C', 'Freestyle Limited Compound'), ('FS-R', 'Freestyle Limited Recurve'), ('FU', 'Freestyle Unlimited'), ('HB', 'Historic Longbow'), ('LB', 'Longbow'), ('TR', 'Traditional Recurve')], max_length=5, verbose_name='Shooting style')),
                ('score', models.IntegerField(verbose_name='Record score')),
                ('scope', models.CharField(blank=True, default='FAAE', max_length=50, verbose_name='record scope (FAAE/EM/MM)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages', to='api.Series'),
        ),
        migrations.AddField(
            model_name='series',
            name='points_max',
            field=models.IntegerField(default=10, max_length=2, verbose_name='Maximum point score for the first place'),
        ),
    ]
