# Generated by Django 3.0.2 on 2020-05-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200527_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='points_max',
            field=models.IntegerField(default=10, verbose_name='Maximum point score for the first place'),
        ),
    ]
