# Generated by Django 3.0.2 on 2020-05-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200527_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='event',
        ),
        migrations.AddField(
            model_name='record',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of achievement'),
        ),
    ]
