# Generated by Django 3.0.2 on 2020-06-02 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200527_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['style', 'age_group']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='admins',
        ),
        migrations.AddField(
            model_name='participant',
            name='level_class',
            field=models.CharField(blank=True, default='', max_length=1, verbose_name='Level class'),
        ),
        migrations.AddField(
            model_name='record',
            name='round',
            field=models.CharField(default='', max_length=255, verbose_name='Round'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='group',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='group_target',
            field=models.IntegerField(default=1, verbose_name='End nr'),
        ),
        migrations.AlterField(
            model_name='record',
            name='scope',
            field=models.CharField(blank=True, default='FAAE', max_length=50, verbose_name='record scope (personal/FAAE/EM/MM)'),
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('style', 'age_group', 'scope')},
        ),
        migrations.CreateModel(
            name='LevelClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('*', '*')], max_length=1, verbose_name='Level')),
                ('age_group', models.CharField(choices=[('C', 'Cub'), ('J', 'Junior'), ('A', 'Adult'), ('V', 'Veteran'), ('S', 'Senior')], max_length=1, verbose_name='age group')),
                ('style', models.CharField(choices=[('BB-C', 'Barebow Compound'), ('BB-R', 'Barebow Recurve'), ('BH-C', 'Bowhunter Compound'), ('BH-R', 'Bowhunter Recurve'), ('BL', 'Bowhunter Limited'), ('BU', 'Bowhunter Unlimited'), ('FS-C', 'Freestyle Limited Compound'), ('FS-R', 'Freestyle Limited Recurve'), ('FU', 'Freestyle Unlimited'), ('HB', 'Historic Longbow'), ('LB', 'Longbow'), ('TR', 'Traditional Recurve')], max_length=5, verbose_name='Shooting style')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date of achievement')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.EmailField(blank=True, max_length=254, null=True)),
                ('archer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_classes', to='api.Archer')),
            ],
            options={
                'ordering': ['style', 'age_group'],
                'unique_together': {('style', 'age_group', 'archer')},
            },
        ),
    ]
