# Generated by Django 3.0.2 on 2020-06-02 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200602_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='admins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_admins', to=settings.AUTH_USER_MODEL),
        ),
    ]
