# Generated by Django 3.0.2 on 2020-06-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_event_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='event',
            field=models.CharField(blank=True, max_length=255, verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='series',
            name='participant_restriction',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='i.e. "club__association:FAAE"'),
        ),
    ]
