# Generated by Django 3.0.2 on 2020-06-04 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200603_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='admins',
        ),
        migrations.AddField(
            model_name='event',
            name='admins',
            field=models.ManyToManyField(related_name='events_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='series',
            name='participant_restriction',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='i.e. "archer__club__association:FAAE"'),
        ),
    ]
