# Generated by Django 3.0.2 on 2020-06-16 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200611_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['-date_end']},
        ),
    ]
