# Generated by Django 3.0.2 on 2020-06-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200616_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='group',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Group'),
        ),
    ]
