# Generated by Django 3.0.2 on 2020-06-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200617_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='use_level_class',
            field=models.BooleanField(default=False, verbose_name='Use Level Classes'),
        ),
        migrations.AlterField(
            model_name='event',
            name='catering',
            field=models.BooleanField(default=False, verbose_name='Provide catering'),
        ),
        migrations.AlterField(
            model_name='levelclass',
            name='style',
            field=models.CharField(choices=[('BB-C', 'Barebow Compound'), ('BB-R', 'Barebow Recurve'), ('BH-C', 'Bowhunter Compound'), ('BH-R', 'Bowhunter Recurve'), ('BL', 'Bowhunter Limited'), ('BU', 'Bowhunter Unlimited'), ('FS-C', 'Freestyle Limited Compound'), ('FS-R', 'Freestyle Limited Recurve'), ('FU', 'Freestyle Unlimited'), ('HB', 'Historic Longbow'), ('LB', 'Longbow'), ('TR', 'Traditional Recurve'), ('**', 'Variable')], max_length=5, verbose_name='Shooting style'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='style',
            field=models.CharField(choices=[('BB-C', 'Barebow Compound'), ('BB-R', 'Barebow Recurve'), ('BH-C', 'Bowhunter Compound'), ('BH-R', 'Bowhunter Recurve'), ('BL', 'Bowhunter Limited'), ('BU', 'Bowhunter Unlimited'), ('FS-C', 'Freestyle Limited Compound'), ('FS-R', 'Freestyle Limited Recurve'), ('FU', 'Freestyle Unlimited'), ('HB', 'Historic Longbow'), ('LB', 'Longbow'), ('TR', 'Traditional Recurve'), ('**', 'Variable')], max_length=5, verbose_name='Shooting style'),
        ),
        migrations.AlterField(
            model_name='record',
            name='style',
            field=models.CharField(choices=[('BB-C', 'Barebow Compound'), ('BB-R', 'Barebow Recurve'), ('BH-C', 'Bowhunter Compound'), ('BH-R', 'Bowhunter Recurve'), ('BL', 'Bowhunter Limited'), ('BU', 'Bowhunter Unlimited'), ('FS-C', 'Freestyle Limited Compound'), ('FS-R', 'Freestyle Limited Recurve'), ('FU', 'Freestyle Unlimited'), ('HB', 'Historic Longbow'), ('LB', 'Longbow'), ('TR', 'Traditional Recurve'), ('**', 'Variable')], max_length=5, verbose_name='Shooting style'),
        ),
    ]
