# Generated by Django 3.0.8 on 2020-07-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200629_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['age_group', 'style', '-date']},
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('u', 'Unit'), ('r', 'Round'), ('s', 'Shootoff')], default='r', max_length=1, verbose_name='Round/Unit'),
        ),
        migrations.AlterField(
            model_name='record',
            name='round',
            field=models.CharField(choices=[('flint', 'IFAA Flint'), ('indoor', 'IFAA Indoor'), ('animal', 'IFAA Animal Marked Distances'), ('field', 'IFAA Field'), ('hunter', 'IFAA Hunter')], max_length=255, verbose_name='Round'),
        ),
        migrations.AlterField(
            model_name='record',
            name='scope',
            field=models.CharField(default='EE', max_length=50, verbose_name='record scope (EE/EU/W)'),
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('style', 'round', 'age_group', 'scope', 'date')},
        ),
    ]
