# Generated by Django 3.0.8 on 2020-07-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200714_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ignore_gender',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='age_style to merge gender (A_TR, V_TR)'),
        ),
    ]
