# Generated by Django 3.0.8 on 2020-07-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_event_ignore_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='ignore_gender',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='age_style to merge gender (A_TR, V_TR)'),
        ),
    ]
