# Generated by Django 3.0.8 on 2020-07-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_series_ignore_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='round',
            field=models.CharField(choices=[('flint', 'IFAA Flint'), ('indoor', 'IFAA Indoor'), ('animal', 'IFAA Animal (Marked Distances)'), ('field', 'IFAA Field'), ('hunter', 'IFAA Hunter')], max_length=255, verbose_name='Round'),
        ),
    ]
