# Generated by Django 3.0.8 on 2020-07-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200714_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1, verbose_name='gender'),
            preserve_default=False,
        ),
    ]
