# Generated by Django 3.0.8 on 2020-08-12 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_record_gender'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('round', 'age_group', 'gender', 'style', 'scope', 'date')},
        ),
    ]
