# Generated by Django 3.2.5 on 2021-07-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20210513_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelclass',
            name='age_group',
            field=models.CharField(choices=[('T', 'Tidet'), ('C', 'Cub'), ('CA', 'Cadet'), ('J', 'Junior'), ('YA', 'Young Adult'), ('A', 'Adult'), ('V', 'Veteran'), ('O', 'Open')], max_length=2, verbose_name='age group'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='age_group',
            field=models.CharField(choices=[('T', 'Tidet'), ('C', 'Cub'), ('CA', 'Cadet'), ('J', 'Junior'), ('YA', 'Young Adult'), ('A', 'Adult'), ('V', 'Veteran'), ('O', 'Open')], max_length=2, verbose_name='age group'),
        ),
        migrations.AlterField(
            model_name='record',
            name='age_group',
            field=models.CharField(choices=[('T', 'Tidet'), ('C', 'Cub'), ('CA', 'Cadet'), ('J', 'Junior'), ('YA', 'Young Adult'), ('A', 'Adult'), ('V', 'Veteran'), ('O', 'Open')], max_length=2, verbose_name='age group'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
