# Generated by Django 3.2.5 on 2021-07-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20210716_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='judges',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='participant',
            name='group_target',
            field=models.IntegerField(default=1, verbose_name='Target nr'),
        ),
    ]
