# Generated by Django 4.0.2 on 2022-02-10 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20210722_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='group',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='group_target',
            new_name='group',
        ),
        migrations.AlterField(
            model_name='participant',
            name='session',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Session'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='group',
            field=models.IntegerField(default=1, verbose_name='Group nr'),
        ),
        migrations.AddField(
            model_name='participant',
            name='archer_rep',
            field=models.CharField(default='|', max_length=20, verbose_name='archer representation in a form "club_short|association_short"'),
        ),
        migrations.AddField(
            model_name='participant',
            name='full_name',
            field=models.CharField(default='Unnamed archer', max_length=150, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='U', max_length=1, verbose_name='gender'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='club',
            name='association',
        ),
        migrations.AlterField(
            model_name='levelclass',
            name='age_group',
            field=models.CharField(choices=[('T', 'Tidet'), ('C', 'Cub'), ('CA', 'Cadet'), ('J', 'Junior'), ('YA', 'Young Adult'), ('A', 'Adult'), ('V', 'Veteran'), ('O', 'Open')], max_length=3, verbose_name='age group'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='age_group',
            field=models.CharField(choices=[('T', 'Tidet'), ('C', 'Cub'), ('CA', 'Cadet'), ('J', 'Junior'), ('YA', 'Young Adult'), ('A', 'Adult'), ('V', 'Veteran'), ('O', 'Open')], max_length=3, verbose_name='age group'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='archer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='api.archer'),
        ),
        migrations.AlterField(
            model_name='record',
            name='age_group',
            field=models.CharField(choices=[('T', 'Tidet'), ('C', 'Cub'), ('CA', 'Cadet'), ('J', 'Junior'), ('YA', 'Young Adult'), ('A', 'Adult'), ('V', 'Veteran'), ('O', 'Open')], max_length=3, verbose_name='age group'),
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed archery association', max_length=150, verbose_name='Organisation name')),
                ('name_short', models.CharField(blank=True, default='***', max_length=10, verbose_name='Organisation name short')),
                ('contact', models.TextField(verbose_name='Contact Information')),
                ('description', models.TextField()),
                ('admins', models.ManyToManyField(blank=True, related_name='admin_association', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associations_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='club',
            name='association',
            field=models.ManyToManyField(blank=True, related_name='clubs', to='api.Association'),
        ),
    ]
