# Generated by Django 4.0.2 on 2022-03-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_participant_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelclass',
            name='age_group',
            field=models.CharField(choices=[('C', 'Cub'), ('J', 'Junior'), ('YA', 'Young Adult'), ('A', 'Adult'), ('V', 'Veteran'), ('S', 'Senior'), ('O', 'Open'), ('U13', 'Under 13'), ('U15', 'Under 15'), ('U18', 'Under 18'), ('U21', 'Under 21'), ('50+', '50+')], max_length=3, verbose_name='age group'),
        ),
        migrations.AlterField(
            model_name='levelclass',
            name='style',
            field=models.CharField(choices=[('BB-C', 'Barebow Compound'), ('BB-R', 'Barebow Recurve'), ('BH-C', 'Bowhunter Compound'), ('BH-R', 'Bowhunter Recurve'), ('BL', 'Bowhunter Limited'), ('BU', 'Bowhunter Unlimited'), ('FS-C', 'Freestyle Limited Compound'), ('FS-R', 'Freestyle Limited Recurve'), ('FU', 'Freestyle Unlimited'), ('HB', 'Historic Longbow'), ('LB', 'Longbow'), ('TR', 'Traditional Recurve'), ('**', 'Variable'), ('R', 'Recurve'), ('C', 'Compound'), ('B', 'Barebow'), ('T', 'Traditional'), ('L', 'Longbow')], max_length=5, verbose_name='Shooting style'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='age_group',
            field=models.CharField(choices=[('C', 'Cub'), ('J', 'Junior'), ('YA', 'Young Adult'), ('A', 'Adult'), ('V', 'Veteran'), ('S', 'Senior'), ('O', 'Open'), ('U13', 'Under 13'), ('U15', 'Under 15'), ('U18', 'Under 18'), ('U21', 'Under 21'), ('50+', '50+')], max_length=3, verbose_name='age group'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='style',
            field=models.CharField(choices=[('BB-C', 'Barebow Compound'), ('BB-R', 'Barebow Recurve'), ('BH-C', 'Bowhunter Compound'), ('BH-R', 'Bowhunter Recurve'), ('BL', 'Bowhunter Limited'), ('BU', 'Bowhunter Unlimited'), ('FS-C', 'Freestyle Limited Compound'), ('FS-R', 'Freestyle Limited Recurve'), ('FU', 'Freestyle Unlimited'), ('HB', 'Historic Longbow'), ('LB', 'Longbow'), ('TR', 'Traditional Recurve'), ('**', 'Variable'), ('R', 'Recurve'), ('C', 'Compound'), ('B', 'Barebow'), ('T', 'Traditional'), ('L', 'Longbow')], max_length=5, verbose_name='Shooting style'),
        ),
        migrations.AlterField(
            model_name='record',
            name='age_group',
            field=models.CharField(choices=[('C', 'Cub'), ('J', 'Junior'), ('YA', 'Young Adult'), ('A', 'Adult'), ('V', 'Veteran'), ('S', 'Senior'), ('O', 'Open'), ('U13', 'Under 13'), ('U15', 'Under 15'), ('U18', 'Under 18'), ('U21', 'Under 21'), ('50+', '50+')], max_length=3, verbose_name='age group'),
        ),
        migrations.AlterField(
            model_name='record',
            name='style',
            field=models.CharField(choices=[('BB-C', 'Barebow Compound'), ('BB-R', 'Barebow Recurve'), ('BH-C', 'Bowhunter Compound'), ('BH-R', 'Bowhunter Recurve'), ('BL', 'Bowhunter Limited'), ('BU', 'Bowhunter Unlimited'), ('FS-C', 'Freestyle Limited Compound'), ('FS-R', 'Freestyle Limited Recurve'), ('FU', 'Freestyle Unlimited'), ('HB', 'Historic Longbow'), ('LB', 'Longbow'), ('TR', 'Traditional Recurve'), ('**', 'Variable'), ('R', 'Recurve'), ('C', 'Compound'), ('B', 'Barebow'), ('T', 'Traditional'), ('L', 'Longbow')], max_length=5, verbose_name='Shooting style'),
        ),
    ]
