# Generated by Django 4.0.2 on 2022-03-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_event_association'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scorecard',
            options={'ordering': ['participant__target_pos']},
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='group_pos',
            new_name='target_pos',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='group',
            new_name='target',
        ),
        migrations.AlterField(
            model_name='participant',
            name='target',
            field=models.IntegerField(default=1, verbose_name='Target nr'),
        ),
    ]
