# Generated by Django 4.0.2 on 2022-04-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_scorecard_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scorecard',
            options={'ordering': ['round__ord', 'participant__target_pos']},
        ),
        migrations.AddField(
            model_name='scorecard',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='Scorecards has been checked by organizer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ignore_gender',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='age_style to merge gender (A_TR, V_TR, all)'),
        ),
        migrations.AlterField(
            model_name='record',
            name='scope',
            field=models.CharField(default='FAAE', max_length=50, verbose_name='record scope (association_short(i.e FAAE)/EU/W)'),
        ),
        migrations.AlterField(
            model_name='series',
            name='ignore_gender',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='age_style to merge gender (A_TR, V_TR, all)'),
        ),
        migrations.AlterField(
            model_name='series',
            name='participant_restriction',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='i.e. "archer_rep__contains:FAAE"'),
        ),
    ]
