# Generated by Django 3.2.12 on 2022-05-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_scorecard_options_scorecard_checked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_association',
            field=models.BooleanField(default=False, verbose_name='Show association instead of club in participant list'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='pr',
            field=models.FloatField(default=None, null=True, verbose_name='Progress'),
        ),
    ]
