# Generated by Django 3.2.12 on 2022-08-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20220508_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelclass',
            name='age_group',
            field=models.CharField(choices=[('C', 'Cub'), ('J', 'Junior'), ('YA', 'Young Adult'), ('A', 'Adult'), ('V', 'Veteran'), ('S', 'Senior'), ('P', 'Professional'), ('O', 'Open'), ('U13', 'Under 13'), ('U15', 'Under 15'), ('U18', 'Under 18'), ('U21', 'Under 21'), ('50+', '50+')], max_length=3, verbose_name='age group'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='age_group',
            field=models.CharField(choices=[('C', 'Cub'), ('J', 'Junior'), ('YA', 'Young Adult'), ('A', 'Adult'), ('V', 'Veteran'), ('S', 'Senior'), ('P', 'Professional'), ('O', 'Open'), ('U13', 'Under 13'), ('U15', 'Under 15'), ('U18', 'Under 18'), ('U21', 'Under 21'), ('50+', '50+')], max_length=3, verbose_name='age group'),
        ),
        migrations.AlterField(
            model_name='record',
            name='age_group',
            field=models.CharField(choices=[('C', 'Cub'), ('J', 'Junior'), ('YA', 'Young Adult'), ('A', 'Adult'), ('V', 'Veteran'), ('S', 'Senior'), ('P', 'Professional'), ('O', 'Open'), ('U13', 'Under 13'), ('U15', 'Under 15'), ('U18', 'Under 18'), ('U21', 'Under 21'), ('50+', '50+')], max_length=3, verbose_name='age group'),
        ),
    ]
