# Generated by Django 4.2.3 on 2023-08-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20220806_0855'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LevelClass',
        ),
    ]
